version: '3.9'

volumes:
  plugin_data:
  worlds:
  db_data:

services:
  server:
    build:
      context: .
      args:
        uid: 10002
        gid: 10002
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - 25565:25565
    depends_on:
      - db
    environment:
      HEAP_SIZE: '2G'
    volumes:
      - plugin_data:/plugin_data
      - worlds:/worlds
  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    env_file:
      - ./secrets/db.env

  backup:
    hostname: server_backup
    build: ./backup
    environment:
      RCON_HOST: server
      RCON_PORT: 25575
      RESTIC_REPOSITORY: rclone:backend:bucket
      BACKUP_CRON: "0 */12 * * *"
      RESTIC_FORGET_ARGS: "--prune --keep-last 4 --keep-daily 5 --keep-weekly 4 --keep-monthly 6 --keep-yearly 3"
    volumes:
      - ~/.config/rclone:/root/.config/rclone
      - ./backup/hooks:/hooks
      - ./secrets/.my.cnf:/root/.my.cnf
      - worlds:/data/worlds:ro
      - plugin_data:/data/plugin_data:ro
    env_file:
      - ./secrets/backup.env
