version: '3.9'

volumes:
  plugin_data:
  worlds:

services:
  server:
    build:
      context: .
      args:
        uid: 10002
        gid: 10002
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - 25565:25565
    depends_on:
      - db
    environment:
      HEAP_SIZE: '2G'
    volumes:
      - plugin_data:/plugin_data
      - worlds:/worlds
  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    env_file:
      - ./secrets/db.env

